"""Domain models, contexts, and plan contracts for the Intelligent Recovery Orchestrator."""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional
import uuid

from app.models.enums import (
    FailureCategory,
    MerchantTier,
    PaymentLifecycleState,
    PaymentMethod,
    RecoveryState,
    RecoveryStrategy,
    RetryabilityClass,
    RouteStatus,
)


@dataclass
class PaymentRecoveryContext:
    """
    Compact, relevant context required for deterministic recovery planning.
    Assembled without leaking raw relational or memory-heavy database objects.
    """
    payment_id: uuid.UUID
    merchant_id: uuid.UUID
    customer_id: uuid.UUID
    amount_inr: Decimal
    payment_method: PaymentMethod
    route_id: str
    route_health_score: float
    route_is_active: bool
    route_status: RouteStatus
    failure_category: FailureCategory
    error_code: str
    reason: str
    attempt_number: int
    failure_created_at: datetime
    merchant_tier: MerchantTier
    merchant_recovery_enabled: bool
    merchant_max_auto_retries: int
    merchant_min_recovery_amount_inr: Decimal
    merchant_auto_escalate_threshold_inr: Decimal
    available_alternative_routes: List[str] = field(default_factory=list)
    correlation_id: str = ""
    causation_id: Optional[str] = None
    payment_status: Optional[PaymentLifecycleState] = None


@dataclass
class RecoveryPlan:
    """
    Explainable recovery plan generated by the deterministic decision engine.
    Contains strategy, target parameters, and human-readable justification.
    """
    strategy: RecoveryStrategy
    retryability: RetryabilityClass
    target_route_id: Optional[str] = None
    suggested_backoff_sec: Optional[float] = None
    notification_channel: Optional[str] = None
    notification_template: Optional[str] = None
    decision_confidence: float = 1.0  # Deterministic rule certainty (1.0 = explicit rule, 0.0 = fallback)
    explanation: str = ""
    parameters: Dict[str, Any] = field(default_factory=dict)
    guards_evaluated: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy": self.strategy.value,
            "retryability": self.retryability.value,
            "target_route_id": self.target_route_id,
            "suggested_backoff_sec": self.suggested_backoff_sec,
            "notification_channel": self.notification_channel,
            "notification_template": self.notification_template,
            "decision_confidence": self.decision_confidence,
            "explanation": self.explanation,
            "parameters": self.parameters,
            "guards_evaluated": self.guards_evaluated,
        }


@dataclass
class GuardEvaluationResult:
    """Outcome of evaluating deterministic recovery eligibility guards."""
    is_approved: bool
    stop_reason: Optional[str] = None
    is_escalated: bool = False
    guards_checked: List[str] = field(default_factory=list)
    violated_guards: List[str] = field(default_factory=list)
    details: Dict[str, Any] = field(default_factory=dict)
