"""add_orchestrator_fields_to_merchants_and_recovery_cases

Revision ID: 08109477ba6b
Revises: 74146b281c03
Create Date: 2026-09-04 23:25:34.594980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08109477ba6b'
down_revision: Union[str, Sequence[str], None] = '74146b281c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('min_recovery_amount_inr', sa.Numeric(precision=12, scale=2), server_default="50.00", nullable=False))
    op.add_column('recovery_cases', sa.Column('recovery_state', sa.Enum('FAILED', 'CLASSIFIED', 'RECOVERY_PLANNED', 'GUARD_PENDING', 'APPROVED', 'EXECUTING', 'RECOVERY_SUCCEEDED', 'RECOVERY_FAILED', 'ESCALATED', 'STOPPED', name='recoverystate', native_enum=False), server_default="FAILED", nullable=False))
    op.add_column('recovery_cases', sa.Column('plan_details', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_recovery_cases_recovery_state'), 'recovery_cases', ['recovery_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_recovery_state'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'plan_details')
    op.drop_column('recovery_cases', 'recovery_state')
    op.drop_column('merchants', 'min_recovery_amount_inr')
    # ### end Alembic commands ###
