"""initial_payment_domain

Revision ID: 4ee34b5910a4
Revises: 
Create Date: 2026-09-04 22:37:48.247126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee34b5910a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('email_masked', sa.String(length=255), nullable=False),
    sa.Column('phone_masked', sa.String(length=50), nullable=False),
    sa.Column('historical_success_rate', sa.Float(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('historical_success_rate >= 0.0 AND historical_success_rate <= 1.0', name='check_customer_success_rate_range'),
    sa.CheckConstraint('risk_score >= 0.0 AND risk_score <= 1.0', name='check_customer_risk_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mcc', sa.String(length=10), nullable=False, comment='Merchant Category Code'),
    sa.Column('tier', sa.Enum('ENTERPRISE', 'GROWTH', 'STARTUP', name='merchanttier', native_enum=False), nullable=False),
    sa.Column('recovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_auto_retries', sa.Integer(), nullable=False),
    sa.Column('max_recovery_amount_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('auto_escalate_threshold_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_table('payment_routes',
    sa.Column('id', sa.String(length=50), nullable=False, comment='Route identifier e.g. ROUTE_HDFC_UPI, ROUTE_AXIS_CARDS'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NETBANKING', 'WALLET', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', name='routestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('health_score >= 0.0 AND health_score <= 1.0', name='check_route_health_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_routes_payment_method'), 'payment_routes', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payment_routes_status'), 'payment_routes', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NETBANKING', 'WALLET', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('preferred_route_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'SUCCESS', 'FAILED', 'RECOVERY_PENDING', 'RECOVERING', 'RECOVERED', 'ESCALATED', 'STOPPED', name='paymentlifecyclestate', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('final_error_code', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_inr > 0', name='check_payment_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_route_id'], ['payment_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_final_error_code'), 'payments', ['final_error_code'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NETBANKING', 'WALLET', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', name='attemptstatus', native_enum=False), nullable=False),
    sa.Column('gateway_ref_id', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['payment_routes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'attempt_number', name='uq_payment_attempt_number')
    )
    op.create_index(op.f('ix_payment_attempts_payment_id'), 'payment_attempts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_route_id'), 'payment_attempts', ['route_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'SUCCESS', 'FAILED', 'RECOVERY_PENDING', 'RECOVERING', 'RECOVERED', 'ESCALATED', 'STOPPED', name='paymentlifecyclestate', native_enum=False), nullable=False),
    sa.Column('strategy', sa.Enum('NONE', 'DETERMINISTIC_RETRY_BACKOFF', 'ROUTE_FAILOVER', 'NOTIFY_CUSTOMER_LINK', 'MANUAL_REVIEW', 'TERMINAL_ABANDON', name='recoverystrategy', native_enum=False), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('estimated_recovery_rate', sa.Float(), nullable=True),
    sa.Column('recovered_amount_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=True)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_table('payment_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('failure_category', sa.Enum('TRANSIENT', 'ROUTE_DEGRADATION', 'CUSTOMER_ACTION_REQUIRED', 'PERMANENT', 'FRAUD', name='failurecategory', native_enum=False), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recoverable', sa.Boolean(), nullable=False),
    sa.Column('suggested_backoff_sec', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['payment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_failures_attempt_id'), 'payment_failures', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_payment_failures_error_code'), 'payment_failures', ['error_code'], unique=False)
    op.create_index(op.f('ix_payment_failures_failure_category'), 'payment_failures', ['failure_category'], unique=False)
    op.create_index(op.f('ix_payment_failures_payment_id'), 'payment_failures', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_failures_recoverable'), 'payment_failures', ['recoverable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_failures_recoverable'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_payment_id'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_failure_category'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_error_code'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_attempt_id'), table_name='payment_failures')
    op.drop_table('payment_failures')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_route_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_payment_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_final_error_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_routes_status'), table_name='payment_routes')
    op.drop_index(op.f('ix_payment_routes_payment_method'), table_name='payment_routes')
    op.drop_table('payment_routes')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
