"""add_processed_events_and_notifications

Revision ID: 74146b281c03
Revises: 4ee34b5910a4
Create Date: 2026-09-04 22:55:54.838375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74146b281c03'
down_revision: Union[str, Sequence[str], None] = '4ee34b5910a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False, comment='Unique event identifier from event envelope'),
    sa.Column('consumer_name', sa.String(length=100), nullable=False, comment='Consumer group or worker identifier (e.g. iro-recovery-group)'),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_name')
    )
    op.create_index(op.f('ix_processed_events_event_type'), 'processed_events', ['event_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_payment_id'), 'notifications', ['payment_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_payment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_processed_events_event_type'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
