"""add_idempotency_key_to_payment_attempts

Revision ID: b55e745431e0
Revises: 08109477ba6b
Create Date: 2026-09-05 12:59:29.384479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55e745431e0'
down_revision: Union[str, Sequence[str], None] = '08109477ba6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_attempts', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_payment_attempts_idempotency_key'), 'payment_attempts', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_idempotency_key'), table_name='payment_attempts')
    op.drop_column('payment_attempts', 'idempotency_key')
    # ### end Alembic commands ###
